# Generated by Django 4.1.5 on 2023-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="made_by",
            field=models.CharField(max_length=128),
        ),
    ]
