# Generated by Django 4.1.5 on 2023-01-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=128)),
                ("price", models.FloatField()),
                ("data", models.FloatField()),
                ("sms", models.PositiveIntegerField()),
                ("validity", models.PositiveBigIntegerField()),
            ],
        ),
    ]
