# Generated by Django 4.1.5 on 2023-01-09 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AirtelPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("data", models.FloatField()),
                ("sms", models.PositiveIntegerField()),
                ("validity", models.PositiveBigIntegerField()),
                (
                    "company",
                    models.CharField(default="Airtel", editable=False, max_length=128),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="JioPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("data", models.FloatField()),
                ("sms", models.PositiveIntegerField()),
                ("validity", models.PositiveBigIntegerField()),
                (
                    "company",
                    models.CharField(default="Jio", editable=False, max_length=128),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ViPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("data", models.FloatField()),
                ("sms", models.PositiveIntegerField()),
                ("validity", models.PositiveBigIntegerField()),
                (
                    "company",
                    models.CharField(default="VI", editable=False, max_length=128),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
